import type { Metadata } from "next";
import {
	Roboto_Flex,
	Roboto_Mono,
	Roboto_Serif,
	Shadows_Into_Light,
} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import Background from "@/components/background";
import PathProvider from "@/components/path-provider";

const roboto = Roboto_Flex({
	subsets: ["latin"],
	variable: "--font-roboto",
	display: "swap",
	axes: [
		"GRAD",
		"opsz",
		"wdth",
		"XOPQ",
		"XTRA",
		"YOPQ",
		"YTAS",
		"YTUC",
		"YTDE",
		"YTFI",
		"YTLC",
		"YTUC",
		"slnt",
	],
});

const robotoMono = Roboto_Mono({
	subsets: ["latin"],
	variable: "--font-roboto-mono",
	display: "swap",
	weight: "variable",
});

const robotoSerif = Roboto_Serif({
	subsets: ["latin"],
	variable: "--font-roboto-serif",
	display: "swap",
	axes: ["GRAD", "opsz", "wdth"],
});

const shadowsIntoLight = Shadows_Into_Light({
	subsets: ["latin"],
	variable: "--font-shadows-into-light",
	weight: "400",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<PathProvider>
			<html lang="en">
				<body
					className={`${roboto.variable} ${robotoMono.variable} ${robotoSerif.variable} ${shadowsIntoLight.variable} antialiased font-sans`}
				>
					<div className="relative flex flex-col w-full">
						<Navbar />
						<div className="flex min-h-screen content">
							{children}
						</div>
						<Footer />
						<Background />
					</div>
				</body>
			</html>
		</PathProvider>
	);
}
